Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include("users.urls")),
    path("vendors/", include("vendors.urls")),
    path('services/', include("services.urls")),
    path('api/', include('api.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('get-products/', views.get_products, name='get-products'),

    path('get-reviews/<str:handle>/', views.get_reviews, name='get-reviews'),
    path('create-review/<str:handle>/', views.create_review, name='create-review'),

    path('create-or-remove-cart-item/<int:product_pk>/', views.create_or_remove_cart_item, name='create-or-remove-cart-item'),
    path('clear-cart/<int:pk>/', views.clear_cart, name='clear-cart'),
    path('update-cart-item-quantity/<int:pk>/', views.update_cart_item_quantity, name="update-cart-item-quantity"),

    path('create-or-remove-wishlist-item/<int:product_pk>/', views.create_or_remove_wishlist_item, name="create-or-remove-wishlist-item"),
    path('clear-wishlist/<int:pk>/', views.clear_Wishlist, name='clear-wishlist'),

    path('coupon-change/', views.coupon_change, name="coupon-change"),
    path('coupon-apply/', views.coupon_apply, name="coupon-apply"),

    path('create-invoice/', views.create_invoice, name='create-invoice')

]

Ecommerce/products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    path('', views.index, name='home'),

    path('products/<str:handle>/', views.product_detail, name='product-detail'),
    path('products/<str:handle>/download/', views.product_download, name="product-download"),
    path('products/<str:handle>/attachments/download/<int:pk>', views.attachment_download, name="attachment-download"),

    path('cart/', views.cart, name="cart"),

    path('categories/', views.categories_list, name='categories-list'),
    path('categories/<str:category>/', views.category, name="category"),


    path('wishlist/', views.wishlist, name="wishlist"),
    
]

Ecommerce/services/urls.py
from django.urls import path

from . import views

app_name = "services"

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('purchase-guide/', views.purchase_guide, name='purchase-guide'),
    path('terms-of-service/', views.terms_of_service, name='terms-of-service'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('about-us/', views.about_us, name='about-us'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

Ecommerce/vendors/urls.py
from django.urls import path


from . import views


app_name = "vendors"

urlpatterns = [
    path('', views.vendor_list, name="vendor-list"),
    path('<str:handle>/', views.vendor, name='vendor'),

    path('<str:handle>/rating', views.vendor_rating, name='vendor-rating')
]

templates/partials/small-navbar.html
{% load static %}

<div id="small-navbar" class="flex flex-col gap-10 pb-10 fixed min-h-screen w-52 bg-white z-[110] left-0 top-0 shadow md:hidden"
    x-show="smallNavbarShown" x-transition:enter>
    <div style="background-color: #fefefe;" class="w-full py-10 px-10 border-b">
        <img src="{% static 'images/nest.jpg'%}" alt="">
    </div>
    
    <ul class="px-10 flex gap-3 flex-col text-base relative [&>*:where(li)]:p-1 [&>*:where(li)]:cursor-pointer [&>*:where(li)]:transition-colors [&>*:where(li)]:rounded"
        x-data="{pagesShown: false}">
        <li class="flex items-center gap-2 hover:text-amber-500
          {% if chosen == 'deals'%}
          text-amber-500
          {% endif %}">
            <i class="fa-solid fa-fire text-amber-500"></i>
            <p><a href="">Deals</a></p>
        </li>
        <li class="hover:text-green-500
          {% if chosen == 'home' %}
          text-green-500
          {% endif %}"><a href="{% url 'products:home'%}">Home</a></li>
        <li class="hover:text-green-500
                  {% if chosen == 'shop' %}
                  text-green-500
                  {% endif %}"><a href="{% url 'products:shop'%}">Shop</a></li>
        <li class="hover:text-green-500
                  {% if chosen == 'vendors' %}
                  text-green-500
                  {% endif %}"><a href="{% url 'vendors:vendor' 'hello' %}">Vendors</a></li>
        <li class="hover:text-green-500
                  {% if chosen == 'blog' %}
                  text-green-500
                  {% endif %}">Blog</li>
        <li class="flex items-center gap-2 hover:text-green-500" @click="pagesShown = !pagesShown">
            <p>Pages</p>
            <i class="fa-solid fa-chevron-down text-sm"></i>
        </li>
        <ul id="pages-pop"
            class="absolute flex flex-col gap-3 bg-white rounded border shadow-sm px-7 py-4 top-10 -right-8 w-48 *:cursor-pointer text-gray-500"
            x-show="pagesShown" x-on:click.outside="pagesShown = false" x-transition>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:about-us'%}">About Us</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:dashboard'%}">My Dashboard</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:purchase-guide'%}">Purchase Guide</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:privacy-policy'%}">Privacy Policy</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:terms-of-service'%}">Terms of Service</a>
            </li>
        </ul>
        <li class="hover:text-green-500 
        {% if chosen == 'contact'%}
        text-green-500
        {% endif %}"><a href="{% url 'services:contact'%}">Contact</a></li>
    </ul>
</div>

<div id="theme" x-transition x-show="smallNavbarShown" x-on:click="smallNavbarShown = false" class="fixed bg-slate-300/75 z-[100] inset-0"></div>