Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include("users.urls")),
    path("vendors/", include("vendors.urls")),
    path('services/', include("services.urls")),
    path('api/', include('api.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('get-products/', views.get_products, name='get-products'),

    path('get-reviews/<str:handle>/', views.get_reviews, name='get-reviews'),
    path('create-review/<str:handle>/', views.create_review, name='create-review'),

    path('create-or-remove-cart-item/<int:product_pk>/', views.create_or_remove_cart_item, name='create-or-remove-cart-item'),
    path('clear-cart/<int:pk>/', views.clear_cart, name='clear-cart'),
    path('update-cart-item-quantity/<int:pk>/', views.update_cart_item_quantity, name="update-cart-item-quantity"),

    path('create-or-remove-wishlist-item/<int:product_pk>/', views.create_or_remove_wishlist_item, name="create-or-remove-wishlist-item"),
    path('clear-wishlist/<int:pk>/', views.clear_Wishlist, name='clear-wishlist'),

    path('coupon-change/', views.coupon_change, name="coupon-change"),
    path('coupon-apply/', views.coupon_apply, name="coupon-apply"),

    path('create-invoice/', views.create_invoice, name='create-invoice')

]

Ecommerce/products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    path('', views.index, name='home'),

    path('products/<str:handle>/', views.product_detail, name='product-detail'),
    path('products/<str:handle>/download/', views.product_download, name="product-download"),
    path('products/<str:handle>/attachments/download/<int:pk>', views.attachment_download, name="attachment-download"),

    path('cart/', views.cart, name="cart"),

    path('categories/', views.categories_list, name='categories-list'),
    path('categories/<str:category>/', views.category, name="category"),


    path('wishlist/', views.wishlist, name="wishlist"),
    
]

Ecommerce/services/urls.py
from django.urls import path

from . import views

app_name = "services"

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('purchase-guide/', views.purchase_guide, name='purchase-guide'),
    path('terms-of-service/', views.terms_of_service, name='terms-of-service'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('about-us/', views.about_us, name='about-us'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

Ecommerce/users/urls.py
from django.urls import path

from users import views

app_name = "users"


urlpatterns = [
    path('login/', views.login_user, name='login-user'),
    path('register-up/', views.register_user, name='register-user'),
    path('logout-user/', views.logout_user, name='logout-user'),

    path('save-profile-info/', views.save_profile_info, name="save-profile-info"),
    path('save-names/', views.save_names, name="save-names"),

]

Ecommerce/vendors/urls.py
from django.urls import path


from . import views


app_name = "vendors"

urlpatterns = [
    path('', views.vendor_list, name="vendor-list"),
    path('<str:handle>/', views.vendor, name='vendor'),

    path('<str:handle>/rating', views.vendor_rating, name='vendor-rating')
]

Ecommerce/templates/partials/cart-table.html
<table id="cart-items-table" class="rounded-lg min-w-[648px] sm:min-w-full h-fit text-center border-separate [border-spacing:0.25rem]">
    <thead class="bg-gray-50">
        <tr class="*:py-3 *:font-medium *:tracking-wider text-gray-500">
            <th class="!w-24 ">Product</h3>
            <th>Title</h3>
            <th>Unit Price</h3>
            <th>Quantity</h3>
            <th>Subtotal</h3>
            <th>Remove</h3>
            <th>Update</th>
        </tr>
    </thead>
    <tbody class="*:*:px-3 *:*:py-4">
        {% for item in items %}
            <tr id="cart-item" x-data="{
                subtotal: {{item.subtotal}},
                oldQuantity: {{item.quantity}},
                newQuantity: {{item.quantity}},
                price: {{item.product.price}} ,
                removed: false }"
                x-show="!removed"
                data-update-quantity-url="{% url 'api:update-cart-item-quantity' item.pk %}"
                data-remove-cart-item-url="{% url 'api:create-or-remove-cart-item' item.product.pk %}">
                <td class="pl-2">
                    <img src="{{item.product.get_display_image}}" alt="" class="rounded-lg object-cover size-28">
                </td>
                <td>{{item.product.name}}</td>
                <td>${{item.product.price}}</td>
                <td>
                    <input type="number" name="quantity" id="quantity" class="w-14 border p-1 outline-none rounded-lg" value="{{item.quantity}}"
                    x-on:change="subtotal = parseFloat( ( price * $el.value ).toFixed(2) );" min="0" max="20"
                    x-model="newQuantity">
                </td>
                <td x-text="`$${subtotal}`"></td>
                <td x-on:click="numberOfItems --; cartTotal -= subtotal;removed= true" id="remove-btn">
                    <div class="cursor-pointer"><i class="fa-regular fa-trash-can"></i></div>
                </td>
                <td id="update-quantity-btn" x-on:click="
                if (oldQuantity == newQuantity)  return;
                cartSubtotal -= parseFloat(( oldQuantity * price ).toFixed(2));
                cartSubtotal += parseFloat((newQuantity * price).toFixed(2) );
                oldQuantity = newQuantity;">
                    <button><i class="fa-solid fa-arrows-rotate"></i></button>
                </td>
            </tr>
        {% endfor %}
        
    </tbody>
</table>

Ecommerce/templates/partials/dashboard-tabs.html
<li class="hover:bg-amber-300" x-on:click="openedIndex = {{forloop.counter0}}"
    :class="openedIndex == {{forloop.counter0}} ? 'bg-green-500 text-white hover:!bg-green-500' : '' " x-transition>
    <i class="{{icon}} text-gray"></i>
    <p>{{ tab }}</p>
</li>

Ecommerce/templates/partials/footer.html
{% load static %}

<footer class="container sm:mx-auto px-4 my-24 xl:max-w-7xl space-y-10">
    <div class="px-5 md:px-20 py-16 border rounded-lg shadow-md bg-cover bg-no-repeat bg-center xl:bg-bottom" 
    style="background-image: url(/static/images/fruits-footer.png)">
        <h1 class="text-2xl">Stay home & get your daily</h1>
        <h1>From Our Shop</h1>
        <br>
        <small class="text-gray-500 text-lg">Start Your Daily Shop With <a href="{% url 'products:home'%}" class="text-green-500">Nest
                Mart</a></small>
    </div>
    <div class="mx-auto max-w-screen-xl text-center py-4 md:p-8 lg:p-10 space-y-5 bg-[#fefefe] rounded-lg">
        <a href="#" class="flex justify-center items-center text-2xl font-semibold text-gray-900 ">
            <img class="mr-2 h-8" src="{% static 'images/nest.jpg' %}" alt="">
        </a>
        <p class="my-6 text-gray-500 ">Open-source library of over 400+ web components and interactive
            elements built for better web.</p>
        <ul class="flex flex-wrap justify-center items-center mb-6 text-gray-900">
            <li>
                <a href="{% url 'services:about-us' %}" class="mr-4 hover:underline md:mr-6 ">About</a>
            </li>
            <li>
                <a href="{% url 'services:contact' %}" class="mr-4 hover:underline md:mr-6">Contact</a>
            </li>
            <li>
                <a href="{% url 'services:privacy-policy' %}" class="mr-4 hover:underline md:mr-6 ">Privacy & Policy</a>
            </li>
            <li>
                <a href="{% url 'services:terms-of-service' %}" class="mr-4 hover:underline md:mr-6">Terms of Service</a>
            </li>
            <li>
                <a href="{% url 'services:dashboard' %}" class="mr-4 hover:underline md:mr-6">Dashboard</a>
            </li>
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6">Contact</a>
            </li>
        </ul>
        <span class="text-sm text-gray-500 sm:text-center">© 2023-2024 <a href="{% url 'products:home' %}" class="hover:underline">Nest™</a>.
            All Rights Reserved.</span>
    </div>
</footer>

Ecommerce/templates/partials/navbar.html
{% load static %}

<div class="border-b border-slate-400 w-full h-8 flex justify-center items-center">
  <div class="flex justify-center sm:justify-between items-center container px-4 text-sm">
    <div>
      <ul class="flex *:border-r gap-2 *:pr-1 *:cursor-pointer text-xs">
        <li><a href="{% url 'services:about-us'%}">About Us</a></li>
        <li><a href="{% url 'services:dashboard'%}">My Account</a></li>
        <li><a href="{% url 'products:wishlist' %}">Wishlist</a></li>
        <li class="border-none"><a href="{% url 'services:dashboard'%}">Order Tracking</a></li>
      </ul>
    </div>
    <div class="hidden sm:block">
      <p>save up 35% off tody!</p>
    </div>
    <div class="hidden lg:block">
      <ul class="flex gap-2">
        <li>
          Need help? Call Us: <a class="text-green-500" href="">+1800 900</a>
        </li>
        <li>English</li>
        <li>USD</li>
      </ul>
    </div>
  </div>
</div>

<div class="h-fit sm:h-28 w-full border-b border-slate-400 flex justify-center items-center"
  style="background-color: #fefefe">
  <div
    class="flex flex-col gap-5 py-5 sm:py-0 justify-center sm:flex-row sm:justify-between items-center container px-4 text-sm sm:gap-4">
    <div class="block">
      <img src="{% static 'images/nest.jpg' %}" alt="" />
    </div>
    <div class="flex-grow lg:max-w-96">
      <form action="" class="flex justify-between items-center border border-slate-400 px-6 h-8 rounded">
        <input type="text" name="" id="" placeholder="Search for items..."
          class="outline-none caret-slate-400 flex-1 placeholder:text-black" />
        <i class="fa-solid fa-magnifying-glass text-green-400 cursor-pointer"></i>
      </form>
    </div>
    <div class="hidden sm:block relative" x-data="{accountOpened: false, wishlistTextOpened : false}">
      <ul class="flex items-center *:h-7 *:flex *:gap-1 *:items-center *:cursor-pointer gap-5">
        <li class="relative" x-on:mouseover="wishlistTextOpened = true"
          x-on:mouseover.outside="wishlistTextOpened = false">
          <i class="fa-regular fa-heart"></i>
          <a href="{% url 'products:wishlist' %}" class="hover:text-green-500 transition-colors">Wishlist</a>
          <span class="hidden bg-white border shadow rounded-xl absolute top-8 -left-5 w-32 p-2 text-center z-[110]"
            x-show="wishlistTextOpened" x-on:mouseenter="wishlistTextOpened = false" x-bind:class="{'hidden': !wishlistTextOpened}" x-transition>Items You
            Liked</span>
        </li>
        <li>
          <i class="fa-solid fa-cart-shopping"></i>
          <a href="{% url 'products:cart' %}" class="hover:text-green-500 transition-colors">Cart</a>
        </li>
        <li x-on:mouseover="accountOpened = true" x-on:mouseover.outside="accountOpened = false">
          <i class="fa-regular fa-circle-user"></i>
          <p class="transition-colors" x-bind:class="accountOpened && 'text-green-500'">Account</p>
          <div id="account-pop" class="hidden absolute bg-white rounded-lg border top-7 -right-2 z-[110] shadow-lg"
            x-bind:class="{'hidden': !accountOpened}" x-show="accountOpened" x-transition>
            <ul class="flex flex-col gap-5 p-3 *:flex *:gap-2 *:items-center *:cursor-pointer">
              <li>
                <i class="fa-regular fa-circle-user"></i>
                <p><a href="{% url 'services:dashboard' %}">My account</a></p>
              </li>
              <li>
                <i class="fa-solid fa-burger"></i>
                <p><a href="{% url 'services:dashboard' %}">Order Tracking</a></p>
              </li>
              <li>
                <i class="fa-regular fa-heart"></i>
                <p><a href="{% url 'products:wishlist' %}">My Wishlist</a></p>
              </li>
              <li>
                <i class="fa-solid fa-arrow-right-to-bracket"></i>
                {% if request.user.is_authenticated %}
                <p><a href="{% url 'services:dashboard' %}">Logout</a></p>
                {% else %}
                <p><a href="{% url 'users:register-user' %}">Sign in</a></p>
                {% endif %}
              </li>
            </ul>
          </div>
        </li>
      </ul>

    </div>
  </div>
</div>

<div class="h-16 w-full border-b border-slate-400 flex justify-center items-center sticky top-0 bg-white shadow-sm z-[100]">
  <div class="container px-4" x-data="{sidebarShown: false, categoriesDropdownShown: false}">
    <div class="relative flex justify-center md:justify-between items-center text-sm gap-5 md:gap-0 ">
      <div class="flex text-base items-center gap-2 bg-green-500 p-2 rounded text-white cursor-pointer hover:bg-green-600 transition-colors"
        x-on:click="categoriesDropdownShown = !categoriesDropdownShown">
        <i class="fa-solid fa-table"></i>
        <p class="text-center text-sm sm:text-base">Browse All Categories</p>
        <i class="fa-solid fa-chevron-down"></i>
      </div>
      <!-- flowbite element -->
      <div id="categories-dropdown" class="border hidden absolute top-12 z-10 bg-white divide-y divide-gray-100 rounded-lg shadow w-44"
        x-show="categoriesDropdownShown" x-bind:class="{'hidden': !categoriesDropdownShown}" x-on:click.outside="categoriesDropdownShown = false" x-transition>
        <ul class="py-2 text-sm text-black bg-white" >
          {% for category in categories_navbar|slice:"4"%}
            <li>
              <a href="{% url 'products:category' category.0 %}" class="block px-4 py-2 hover:bg-gray-100 ">{{category.1|capfirst}}</a>
            </li>
          {% endfor %}
        </ul>
        <div class="py-2">
          <a href="{% url 'products:categories-list'%}" class="block px-4 py-2 text-sm text-green-500 hover:bg-gray-100">See all categories</a>
        </div>
      </div>
      <!-- endelement -->
      <div class="block md:hidden py-1 px-3 rounded bg-gray-400 hover:bg-gray-500 transition-colors text-lg text-white cursor-pointer order-first"
        x-on:click="sidebarShown = true">
        <i class="fa-solid fa-list"></i>
      </div>
      <div class="hidden md:block">
        <ul
          class="flex gap-3 max-md:flex-col text-base relative [&>*:where(li)]:p-1 [&>*:where(li)]:cursor-pointer [&>*:where(li)]:transition-colors [&>*:where(li)]:rounded"
          x-data="{pagesShown: false}">
          <li class="hover:text-green-500
            {% if chosen == 'home' %}
            text-green-500
            {% endif %}"><a href="{% url 'products:home'%}">Home</a></li>
          <li class="hover:text-green-500
                    {% if chosen == 'categories' %}
                    text-green-500
                    {% endif %}"><a href="{% url 'products:categories-list'%}">Categories</a></li>
          <li class="hover:text-green-500
                    {% if chosen == 'vendors' %}
                    text-green-500
                    {% endif %}"><a href="{% url 'vendors:vendor-list' %}">Vendors</a></li>
          <li class="flex items-center gap-2 hover:text-green-500" x-on:click="pagesShown = !pagesShown">
            <p>Pages</p>
            <i class="fa-solid fa-chevron-down text-sm"></i>
          </li>
          <ul id="pages-pop"
            class="absolute hidden flex-col gap-3 bg-white rounded border shadow-sm px-7 py-4 top-10 -right-8 w-48 *:cursor-pointer text-gray-500"
            x-show="pagesShown" x-bind:class="{'hidden': !pagesShown, 'flex': pagesShown}" x-on:click.outside="pagesShown = false" x-transition>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:about-us'%}">About Us</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:dashboard'%}">My Dashboard</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:purchase-guide'%}">Purchase Guide</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:privacy-policy'%}">Privacy Policy</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:terms-of-service'%}">Terms of Service</a></li>
          </ul>
          <li class="hover:text-green-500 
          {% if chosen == 'contact'%}
          text-green-500
          {% endif %}"><a href="{% url 'services:contact'%}">Contact</a></li>
        </ul>
      </div>
      {% include 'partials/sidebar.html' %}
      <div class="items-center gap-3 mr-8 hidden lg:flex">
        <i class="fa-solid fa-headset text-3xl"></i>
        <div class="flex flex-col">
          <p class="text-green-500 text-lg">1900 - 888</p>
          <p class="text-gray">24/7 Support Center</p>
        </div>
      </div>
    </div>
  </div>
</div>

Ecommerce/templates/partials/path.html
<div class=" w-full py-6 border-b border-slate-400 content-center">
    <div class="container flex flex-wrap mx-auto gap-7 px-4 justify-center md:justify-normal items-center text-sm ">
        <a href="{% url 'products:home'%}">
            <div class="text-green-700 flex items-center gap-2">
                <i class="fa-solid fa-house"></i>
                <span>Home</span>
            </div>
        </a>
        <span class="text-green-500"><i class="fa-solid fa-chevron-right"></i></span>
        <a href="{{parent_page_url}}" class="text-green-600">{{ parent_page_name }}</a>
        {% if page_name %}
        <span class="text-green-500"><i class="fa-solid fa-chevron-right"></i></span>
        <span>{{ page_name }}</span>
        {% endif %}
    </div>
</div>

Ecommerce/templates/partials/product-partial.html
{% load static %}

<div id="product" class="border rounded-xl relative px-2 py-2 col-span-2 transition-all hover:shadow hover:border-gray-400"
    x-data="{heartClicked: {% if product.added_to_wishlist %} true {% else %} false {% endif%}}" 
    data-create-or-remove-wishlist-item-url="{% url 'api:create-or-remove-wishlist-item' product.pk %}" data-create-or-remove-cart-item-url="{% url 'api:create-or-remove-cart-item' product.pk %}" 
    data-added-to-cart="{{product.added_to_cart}}">

    <div class="flex flex-col gap-1 ">
        {% if product.discount %}
        <span class="absolute w-16 h-6 text-center content-center text-sm bg-pink-500 text-white top-0 left-0 rounded-ss-xl rounded-ee-xl z-10">
            {{product.discount}}%
        </span>
        {% endif %}
        <div class="w-full border h-56 rounded-lg group realtive overflow-hidden">
            <a href="{{ product.get_absolute_url}}">
                <img src="{{product.get_display_image}}" alt=""
                    class="object-cover size-full transition-transform duration-500 group-hover:scale-125">
            </a>        
            <div class="opacity-0 absolute gap-1 group-hover:opacity-100 flex rounded transition-opacity p-1 top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-gray-50 text-green-700 *:cursor-pointer">
                <div id="add-to-wishlist-btn" class="border-r pr-1 peer/heart" x-data="{heartHovered: false}" x-on:mouseover="heartHovered = true"
                    x-on:mouseleave="heartHovered = false" x-on:click="userLogged ? heartClicked = !heartClicked : userLoggedPopShown = true">
                    <i class="fa-regular fa-heart" x-show="!(heartHovered || heartClicked)" x-transition:enter></i>
                    <i class="fa-solid fa-heart text-red-400" x-show="heartHovered || heartClicked"></i>
                </div>
                <div class="peer/info">
                    <a href="{{product.get_absolute_url}}"><i class="fa-solid fa-circle-info"></i></a>
                    </div>
                <span id="add-to-wishlist-btn"
                    class="w-28 text-white text-sm text-center rounded absolute -top-7 -left-11 p-1 bg-green-500 opacity-0 peer-hover/heart:opacity-100 peer-hover/heart:-top-10 transition-all before:border-8 before:size-3 before:-bottom-3 before:right-12 before:absolute before:border-transparent before:border-t-green-500">Add
                    to WishList</span>
                <span
                    class="w-24 text-white text-sm text-center rounded absolute -top-7 -left-2 p-1 bg-green-500 opacity-0 peer-hover/info:opacity-100 peer-hover/info:-top-10 transition-all before:border-8 before:size-3 before:-bottom-3 before:right-10 before:absolute before:border-transparent before:border-t-green-500">
                    Details
                </span>
            </div>
        </div>
        <small class="text-gray-500 text-xs">{{product.get_category_display }}</small>
        <strong class="font-bold h-12 line-clamp-2">{{product.name}}</strong>
        <span><i class="fa-solid fa-star text-yellow-500 mr-1"></i>{{product.get_total_reviews}}</span>
        <p class="text-sm">
            By <a href="{{product.vendor.get_absolute_url}}" class="text-green-500">{{product.vendor}}</a>
        </p>
        <div class="flex justify-between items-center mt-3">
            <span class="text-green-600 font-bold">{{product.get_new_price}}</span>
            {% if request.user.is_authenticated %}
            <div class="flex items-center gap-2">
                <div id="add-to-cart-btn" class="bg-green-200 hover:bg-green-400 group cursor-pointer transition-colors px-2 py-1 rounded"
                    x-data="{addedToCart: {% if product.added_to_cart %} true {% else %} false {% endif %} }" 
                    x-on:click="addedToCart = true">
                    <div x-show="!addedToCart">
                        <i class="fa-solid fa-cart-shopping"></i>
                        <button class="group-hover:text-white" >Add</button>
                    </div>
                    <i class="fa-solid fa-check group-hover:text-white transition-colors" x-show="addedToCart"></i>
                </div>
                <div id="add-to-wishlist-btn" class="cursor-pointer" x-data="{heartHovered: false}" x-on:mouseover="heartHovered = true" x-on:mouseleave="heartHovered = false"
                    x-on:click="heartClicked = !heartClicked">
                    <i class="fa-regular fa-heart" x-show="!(heartHovered || heartClicked)" x-transition:enter></i>
                    <i class="fa-solid fa-heart text-red-400" x-show="heartHovered || heartClicked"></i>
                </div>
            </div>
            {% endif %}
        </div>
        {% if product.discount %}
        <small class="line-through text-gray-500 text-sm ml-2">{{product.price}}</small>
        {% endif %}
    </div>
</div>

Ecommerce/templates/partials/sidebar.html
{% load static %}

<div id="small-navbar" class="flex flex-col gap-10 pb-10 fixed min-h-screen w-52 bg-white z-[110] left-0 top-0 shadow md:hidden"
    x-show="sidebarShown" x-transition:enter>
    <div style="background-color: #fefefe;" class="w-full py-10 px-10 border-b">
        <img src="{% static 'images/nest.jpg'%}" alt="">
    </div>
    
    <ul class="px-10 flex gap-3 flex-col text-base relative [&>*:where(li)]:p-1 [&>*:where(li)]:cursor-pointer [&>*:where(li)]:transition-colors [&>*:where(li)]:rounded"
        x-data="{pagesShown: false}">
        <li class="flex items-center gap-2 hover:text-amber-500
          {% if chosen == 'deals'%}
          text-amber-500
          {% endif %}">
            <i class="fa-solid fa-fire text-amber-500"></i>
            <p><a href="">Deals</a></p>
        </li>
        <li class="hover:text-green-500
          {% if chosen == 'home' %}
          text-green-500
          {% endif %}"><a href="{% url 'products:home'%}">Home</a></li>
        <li class="hover:text-green-500
                  {% if chosen == 'categories' %}
                  text-green-500
                  {% endif %}"><a href="{% url 'products:categories-list'%}">Categories</a></li>
        <li class="hover:text-green-500
                  {% if chosen == 'vendors' %}
                  text-green-500
                  {% endif %}"><a href="{% url 'vendors:vendor' 'hello' %}">Vendors</a></li>
        <li class="hover:text-green-500
                  {% if chosen == 'blog' %}
                  text-green-500
                  {% endif %}">Blog</li>
        <li class="flex items-center gap-2 hover:text-green-500" @click="pagesShown = !pagesShown">
            <p>Pages</p>
            <i class="fa-solid fa-chevron-down text-sm"></i>
        </li>
        <ul id="pages-pop"
            class="absolute flex flex-col gap-3 bg-white rounded border shadow-sm px-7 py-4 top-10 -right-8 w-48 *:cursor-pointer text-gray-500"
            x-show="pagesShown" x-on:click.outside="pagesShown = false" x-transition>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:about-us'%}">About Us</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:dashboard'%}">My Dashboard</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:purchase-guide'%}">Purchase Guide</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:privacy-policy'%}">Privacy Policy</a></li>
            <li class="hover:text-black transition-colors"><a href="{% url 'services:terms-of-service'%}">Terms of Service</a>
            </li>
        </ul>
        <li class="hover:text-green-500 
        {% if chosen == 'contact'%}
        text-green-500
        {% endif %}"><a href="{% url 'services:contact'%}">Contact</a></li>
    </ul>
</div>

<div id="theme" x-transition x-show="sidebarShown" x-on:click="sidebarShown = false" class="fixed hidden bg-slate-300/75 z-[100] inset-0"
    x-bind:class="{ 'hidden': !sidebarShown }"></div>

Ecommerce/templates/partials/vendor-product-partial.html
<div id="product" class="flex gap-5 items-center" data-create-or-remove-cart-item-url="{% url 'api:create-or-remove-cart-item' product.pk %}"
    data-create-or-remove-wishlist-item-url="{% url 'api:create-or-remove-wishlist-item' product.pk %}">
    <div class="border rounded-lg p-2">
        <a href="{{product.get_absolute_url }}">
            <img src="{{product.image.url}}" alt="" class="rounded-lg size-56">
        </a>
    </div>
    <div class="space-y-3 grow *:w-full">
        <small class="text-sm ">{{product.get_category_display }}</small>
        <a href="{{product.get_absolute_url }}"><h1 class="font-semibold hover:text-green-400 transition-colors">{{product.name}}</h1></a>
        <p class="text-sm">This is the product</p>
        <strong class="block text-green-600 text-xl">
            {{product.get_new_price}} 
            {% if product.discount%}
            <span class="text-gray-500 line-through text-sm">$201.99</span>
            {% endif %}
        </strong>
        <div class="flex gap-3 items-center !w-fit text-white">
            <div id="create-or-remove-cart-item-btn" 
                class="bg-green-500 py-2 px-5 rounded-lg hover:bg-amber-400 transition-colors cursor-pointer"
                x-data="{addedToCart: {% if product.added_to_cart %} true {% else %} false {% endif %} }"
                x-on:click="userLogged ? addedToCart = true : userLoggedPopShown = true">
                <button x-text="addedToCart ? 'Remove from Cart' : 'Add to Cart' ">Add To Cart</button>
            </div>
            <div id="create-or-remove-wishlist-item-btn"  
                class="rounded-lg py-2 bg-green-500 px-3 cursor-pointer"  
                x-data="{heartHovered: false, heartClicked: {% if product.added_to_wishlist %} true {% else %} false {% endif %}}"
                x-on:mouseover="heartHovered = true"
                x-on:mouseleave="heartHovered = false" 
                x-on:click="userLogged ? heartClicked = !heartClicked : userLoggedPopShown = true">
                <i class="fa-regular fa-heart" x-show="!(heartHovered || heartClicked)" x-transition:enter></i>
                <i class="fa-solid fa-heart text-red-400" x-show="heartHovered || heartClicked"></i>
            </div>
        </div>
    </div>

</div>