Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include("users.urls")),
    path("vendors/", include("vendors.urls")),
    path('services/', include("services.urls")),
    path('api/', include('api.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('get-products/', views.get_products, name='get-products'),

    path('get-reviews/<str:handle>/', views.get_reviews, name='get-reviews'),
    path('create-review/<str:handle>/', views.create_review, name='create-review'),

    path('create-or-remove-cart-item/<int:product_pk>/', views.create_or_remove_cart_item, name='create-or-remove-cart-item'),
    path('clear-cart/<int:pk>/', views.clear_cart, name='clear-cart'),
    path('update-cart-item-quantity/<int:pk>/', views.update_cart_item_quantity, name="update-cart-item-quantity"),

    path('create-or-remove-wishlist-item/<int:product_pk>/', views.create_or_remove_wishlist_item, name="create-or-remove-wishlist-item"),
    path('clear-wishlist/<int:pk>/', views.clear_Wishlist, name='clear-wishlist'),

    path('coupon-change/', views.coupon_change, name="coupon-change"),
    path('coupon-apply/', views.coupon_apply, name="coupon-apply"),

    path('create-invoice/', views.create_invoice, name='create-invoice')

]

Ecommerce/products/urls.py
from django.urls import path

from . import views

app_name = "products"

urlpatterns = [
    path('', views.index, name='home'),

    path('products/<str:handle>/', views.product_detail, name='product-detail'),
    path('products/<str:handle>/download/', views.product_download, name="product-download"),
    path('products/<str:handle>/attachments/download/<int:pk>', views.attachment_download, name="attachment-download"),

    path('cart/', views.cart, name="cart"),

    path('categories/', views.categories_list, name='categories-list'),
    path('categories/<str:category>/', views.category, name="category"),


    path('wishlist/', views.wishlist, name="wishlist"),
    
]

Ecommerce/services/urls.py
from django.urls import path

from . import views

app_name = "services"

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('purchase-guide/', views.purchase_guide, name='purchase-guide'),
    path('terms-of-service/', views.terms_of_service, name='terms-of-service'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('about-us/', views.about_us, name='about-us'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

Ecommerce/users/urls.py
from django.urls import path

from users import views

app_name = "users"


urlpatterns = [
    path('login/', views.login_user, name='login-user'),
    path('register-up/', views.register_user, name='register-user'),
    path('logout-user/', views.logout_user, name='logout-user'),

    path('save-profile-info/', views.save_profile_info, name="save-profile-info"),
    path('save-names/', views.save_names, name="save-names"),

]

Ecommerce/vendors/urls.py
from django.urls import path


from . import views


app_name = "vendors"

urlpatterns = [
    path('', views.vendor_list, name="vendor-list"),
    path('<str:handle>/', views.vendor, name='vendor'),

    path('<str:handle>/rating', views.vendor_rating, name='vendor-rating')
]

Ecommerce/vendors/models.py
from django.db import models
from django.db.models import Count, Sum
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse

from cloudinary.models import CloudinaryField
from math import ceil

from . import utils as vendors_utils

from users.models import Profile

class Vendor(models.Model):
    name = models.CharField(max_length=200, unique=True)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)
    image = CloudinaryField(
        'image',
        public_id_prefix=vendors_utils.get_vendor_prefix_id,
        display_name=vendors_utils.get_vendor_display_name,
        blank=True,
        null=True)
    handle = models.CharField(max_length=200, null=True, blank=True)
    opened = models.DateField(null=True, blank=True)
    social_facebook = models.URLField(blank=True, null=True)
    social_twitter = models.URLField(blank=True, null=True)
    social_Instegram = models.URLField(blank=True, null=True)
    social_youtube = models.URLField(blank=True, null=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    @property
    def get_stars_number(self):
        sum_ratings_columns = self.ratings.aggregate(
            sum_ship_rating=Sum('ship_rating'),
            sum_chat_rating=Sum('chat_rating'),
            sum_products_quality_rating=Sum('products_quality_rating')
        )
        sum_ratings = sum_ratings_columns['sum_ship_rating'] + sum_ratings_columns['sum_chat_rating'] + sum_ratings_columns['sum_products_quality_rating']
        return ceil(sum_ratings / (self.ratings.count() * 3))
    
    @property
    def get_ship_rating_percentage(self):
        sum_ship_rating = self.ratings.aggregate(sum_ship_rating=Sum('ship_rating'))['sum_ship_rating']
        return ceil(sum_ship_rating * 100 / (5 * self.ratings.count()))
    
    @property
    def get_chat_rating_percentage(self):
        sum_chat_rating = self.ratings.aggregate(sum_chat_rating=Sum('chat_rating'))['sum_chat_rating']
        return ceil(sum_chat_rating * 100 / (5 * self.ratings.count()))
    
    @property
    def get_products_quality_rating_percentage(self):
        products_quality_rating = self.ratings.aggregate(sum_products_quality_rating=Sum('products_quality_rating'))['sum_products_quality_rating']
        return ceil(products_quality_rating * 100 / (5 * self.ratings.count()))
    

    def get_absolute_url(self):
        return reverse('vendors:vendor', kwargs={'handle': self.handle})
    
    

    def __str__(self):
        return self.name or 'Vendor'
    
    def save(self, *args, **kwargs) -> None:
        if self.name:
            self.handle = slugify(self.name)
        return super().save(*args, **kwargs)
    


class Rating(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='vendor_ratings')
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name='ratings')
    
    ship_rating = models.PositiveSmallIntegerField(validators=[
        MinValueValidator(1), MaxValueValidator(5)
    ])
    chat_rating = models.PositiveSmallIntegerField(validators=[
        MinValueValidator(1), MaxValueValidator(5)
    ])
    products_quality_rating = models.PositiveSmallIntegerField(validators=[
        MinValueValidator(1), MaxValueValidator(5)
    ])

    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.owner.user.username }: {self.vendor.name}'
    

    

Ecommerce/products/forms.py
from django import forms

from .models import Review, CartItem

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['body', 'rating']

class CartItemUpdateForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['quantity']
        

Ecommerce/vendors/forms.py
from django.forms import ModelForm

from .models import Rating


class RatingForm(ModelForm):

    class Meta:
        model = Rating
        fields = ['ship_rating', 'chat_rating', 'products_quality_rating']

Ecommerce/products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import FileResponse
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Count, F


from .models import (Product, 
                    ProductAttachment, 
                    Review, 
                    CategoryChoices, 
                    Cart,
                    Wishlist,
                    Invoice)


def index(request):
    products = Product.objects.select_related('vendor').prefetch_related('reviews')
    categories = CategoryChoices.choices
    context = {'products': products, 'categories': categories}
    return render(request, 'index.html', context=context)


def product_detail(request, handle):
    product = get_object_or_404(Product, handle=handle)
    related_products = Product.objects.filter(category=product.category).exclude(pk=product.pk)
    reviews = product.reviews.all()
    could_review = None
    if request.user.is_authenticated:
        could_review = not Review.objects.filter(product=product, owner=request.user.profile).exists()
    context = {'product': product, 'related_products': related_products, 'could_review': could_review, 'reviews':reviews}
    return render(request, 'product.html', context=context)


def attachment_download(request, handle, pk):
    attachment = get_object_or_404(ProductAttachment, product__handle=handle, pk=pk)
    image = attachment.image.open(mode='rb')
    filename = attachment.image.name

    response = FileResponse(image)
    response['Content-Type'] = 'application/octet-stream'
    response["Content-Disposition"] = f'attachment;filename={filename}'
    return response

def product_download(request, handle):
    product = get_object_or_404(Product, handle=handle)
    image = product.image    
    filename = image.name

    response = FileResponse(image)
    response['Content-Type'] = 'application/octet-stream'
    response["Content-Disposition"] = f'attachment;filename={filename}'
    return response


@login_required
def cart(request):
    cart = get_object_or_404(Cart, owner=request.user.profile)
    items = cart.items.all()
    context = {'items': items, 'cart': cart}
    return render(request, 'cart.html', context=context)


def category(request, category):
    category = CategoryChoices(category)
    products = Product.objects.filter(category=category)
    context = {'products': products, 'category': category}
    return render(request, 'category.html', context=context)

def categories_list(request):
    categories = Product.objects.values('category').annotate(num_products=Count('pk'))
    for item in categories:
        item['category_name'] = CategoryChoices(item['category']).label
        item['category_db'] = item['category']
        del item['category']
    context = {'categories': categories}
    return render(request, 'categories-list.html', context=context)


@login_required
def wishlist(request):
    wishlist, created = Wishlist.objects.get_or_create(owner=request.user.profile)
    items = wishlist.items.all()
    context = {'items': items, 'wishlist': wishlist}
    return render(request, 'wishlist.html', context=context)

Ecommerce/vendors/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError


from .models import Vendor
from .forms import RatingForm

def vendor(request, handle):
    vendor = get_object_or_404(Vendor, handle=handle)
    context={'vendor': vendor}
    return render(request, 'vendor.html', context=context)

def vendor_list(request):
    vendors = Vendor.objects.all()
    context = {'vendors': vendors}
    return render(request, 'vendors_list.html', context=context)


@require_POST
@login_required
def vendor_rating(request, handle):
    vendor = get_object_or_404(Vendor, handle=handle)
    
    data = {}
    for key in request.POST:
        if key == 'csrfmiddlewaretoken':
            continue
        data[key] = int(request.POST[key])
    
    form = RatingForm(data)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.owner = request.user.profile
        obj.vendor = vendor
        obj.save()
    
        return redirect('products:home')
    # print(form.)
    raise ValidationError('something went wrong.')

Ecommerce/templates/categories-list.html
{% extends 'main.html' %}


{% block head %}
<title>Nest | Categories</title>
{% endblock head %}



{% block content %}
{% include 'partials/navbar.html' with chosen="categories" %}
{% include 'partials/path.html' with parent_page_name="Categories" %}

<div class="container mx-auto px-4 my-10 max-w-[800px]">
    <div class="flex gap-10 flex-wrap">
        {% for category in categories %}
        <!-- flowbite element -->
        <div class="max-w-sm p-4 space-y-3 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">{{category.category_name}}</h5>
            <p class="text-gray-500">{{category.num_products}} Product{{category.num_products|pluralize}}</p>
            <a href="{% url 'products:category' category.category_db %}"
                class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-500 rounded-lg hover:bg-green-600 transition-colors focus:ring-4 focus:outline-none focus:ring-green-300">
                See more products
                <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 14 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M1 5h12m0 0L9 1m4 4L9 9" />
                </svg>
            </a>
        </div>
        <!-- end element -->
        {% endfor %}
    </div>
</div>

{% include 'partials/footer.html' %}
{% endblock content %}

Ecommerce/templates/category.html
{% extends 'main.html'%}
{% load static %}


{% block head %}
<title>Nest | category-name</title>
{% endblock head%}


{% block content %}
{% include 'partials/navbar.html' with chosen="categories"%}
{% url 'products:categories-list' as parent_page_url%}
{% include 'partials/path.html' with parent_page_name='Categories' page_name=category.label|capfirst parent_page_url=parent_page_url %}

<div class="container mx-auto px-4 my-5">
    <div class="flex flex-col gap-3 bg-green-100 border rounded-lg py-20 text-center px-4 sm:px-20 sm:text-left">
        <h1 class="font-bold text-4xl">#{{category.label|capfirst}}</h1>
        <div class="flex flex-wrap gap-3 items-center text-sm justify-center sm:justify-normal">
            <a href="{% url 'products:home'%}">
                <div class="text-green-700 flex items-center gap-2">
                    <i class="fa-solid fa-house"></i>
                    <span>Home</span>
                </div>
            </a>
            <span class="text-green-500">&gt;</span>
            <span>{{category.label|capfirst}}</span>
        </div>
    </div>
</div>

<div class="container mx-auto px-4 flex flex-col gap-3"
    x-data="{
        userLoggedPopShown: false,
        userLogged: {% if requset.user.is_authenticated %} true {% else %} false {% endif %},
    }">
    <p>We found {{products.count}} items for you!</p>
    <div class="grid grid-cols-12 gap-y-5">
        <div class="rounded-lg col-span-full flex flex-col gap-y-4">
            <div class="grid max-[430px]:grid-cols-2 grid-cols-4 md:grid-cols-6 lg:grid-cols-8 xl:grid-cols-10 gap-3">
                {% for product in products %}
                    {% include 'partials/product-partial.html' with product=product%}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- flowbite element -->
    <div id="logging-pop-up"
        class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-[150] justify-center items-center"
        x-bind:class="{'hidden': !userLoggedPopShown, 'block': userLoggedPopShown}" x-show="userLoggedPopShown"
        x-on:click.outside="userLoggedPopShown = false">
        <div class="relative p-4 w-full max-w-2xl max-h-full">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <!-- Modal header -->
                <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                    <h3 class="text-2xl font-semibold text-gray-900 dark:text-white">
                        Logging Required
                    </h3>
                    <button type="button" x-on:click="userLoggedPopShown = false"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center">
                        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                        </svg>
                    </button>
                </div>
                <!-- Modal body -->
                <div class="p-4 md:p-5 space-y-4">
                    <p class="text-lg leading-relaxed text-gray-500 dark:text-gray-400">
                        You have to <a href="{% url 'users:login-user' %}" class="text-green-500">login</a> to add to the
                        cart and the wishlist, You're Welcome!
                    </p>
                </div>
                <!-- Modal footer -->
                <div class="flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b dark:border-gray-600">
    
                    <button type="button" x-on:click="userLoggedPopShown = false"
                        class="py-2.5 px-5 ms-3 text-sm font-medium focus:outline-none transition-colors rounded-lg border bg-green-500 text-white hover:bg-green-600 focus:z-10 focus:ring-4 focus:ring-gray-100">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- end element -->
    <div x-show="userLoggedPopShown" id="theme" class="z-[100] hidden fixed inset-0 bg-slate-200/75" x-transition
        x-bind:class="{'hidden': !userLoggedPopShown}"></div>
</div>

{% include 'partials/footer.html' %}
{% endblock content %}

Ecommerce/templates/dashboard.html
{% extends 'main.html'%}
{% load static %}
{% load mytags %}

{% block head %}
<title>Nest | My Account</title>
{% endblock head %}


{% block content %}
{% include 'partials/navbar.html'%}
{% include "partials/path.html" with parent_page_name="Dashboard"%}
<div class="container mx-auto px-4 my-20 xl:max-w-7xl">
    <div x-data="{ openedIndex: 0}">
        <div class="flex gap-10 flex-col md:flex-row">
            <ul class="flex flex-col gap-4 grow h-fit *:transition-colors *:border *:rounded-lg *:cursor-pointer *:shadow *:p-3 *:grow *:flex *:items-center *:gap-3">
                {% with "Profile,Orders,My Address,Account Details,Logout"|split:',' as tablist %}
                    {% for tab in tablist %}
                        {% cycle 'fa-solid fa-user' 'fa-solid fa-burger' 'fa-solid fa-location-dot' 'fa-solid fa-address-book' 'fa-solid fa-arrow-right-to-bracket' as icon silent %}
                        {% include 'partials/dashboard-tabs.html' with tab=tab icon=icon %}
                    {% endfor %}
                {% endwith %}
            </ul>
            <div class="order-first md:order-none grow-[3]" x-show="openedIndex == 0" x-transition:enter>
                <h1 class="font-bold text-3xl pl-2">My Profile</h1>
                <br>
                <hr class="border">
                <br>
                <div class="flex gap-5">
                    <img src="{% if request.user.profile.image %} {{request.user.profile.image.url}}
                                {% else %} {% static 'images/default-account-image.png'%} {% endif %}" alt="" class="rounded-full size-32 object-cover">
                    <div class="flex-grow pr-20 *:border *:rounded-lg *:p-3 space-y-2">
                        <div>Name - {{request.user.username}}</div>
                        <div>Bio - Software Enginner</div>
                        <div>Phone - {{request.user.profile.phone_number}}</div>
                        <div class="border-none">
                            <button class="p-3 bg-green-500 rounded-lg text-white hover:bg-green-600 hover:-translate-y-1 transition-[background-color,transform]"
                                x-on:click="openedIndex = 3">Edit Profile</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="order-first md:order-none grow-[2] overflow-x-auto pb-5" x-show="openedIndex == 1"
                x-transition:enter>
                {% if invoices %}
                <table class="pb-5 pt-3 border rounded-lg min-w-[600px] sm:min-w-full h-fit text-center">
                    <thead class="bg-gray-50  *:*:last:pr-3">
                        <tr class="*:py-3 text-sm *:font-medium *:tracking-wider text-gray-500">
                            <th>Order</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Paid Status</th>
                            <th class="pr-3">Items</th>
                            <th>Total</th>
                            <th>Coupon</th>
                        </tr>
                    </thead>
                    <tbody class="*:*:px-3 *:*:py-4 *:border-b">
                        {% for invoice in invoices %}
                        <tr>
                            <td>{{invoice.name}}</td>
                            <td>{{invoice.created}}</td>
                            <td>{{invoice.delivery_status}}</td>
                            {% if invoice.paid_status %}
                                <td><i class="fa-solid fa-check text-green-500"></i></td>
                            {%else %}
                                <td class="text-red-700">x</td>
                            {% endif %}

                            <td>{{invoice.number_of_items}}</td>
                            <td>${{invoice.total}}</td>
                            {% if invoice.coupon %}
                                <td class="text-green-500">
                                    {{invoice.coupon.name}}
                                </td>
                            {% else %}
                                <td class="">
                                    no coupon
                                </td>
                            {% endif%}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p class="text-center text-lg">You haven't ordered any products yet.</p>
                <p class="text-center text-lg">If you have any products in the <a href="{% url 'products:cart' %}"
                        class="text-green-500">cart</a>, go and complete the payment,</p>
                <p class="text-center text-lg">and if you don't, you could <a href="{% url 'products:home' %}" class="text-green-500">see our
                        amazing products!</a></p>
                {% endif %}                        
            </div>
            
            <div class="grow-[3] space-y-2" x-show="openedIndex == 2" x-transition:enter>
                <label class="font-semibold">Add address | Change Address</label>

                <form action="{% url 'users:save-profile-info' %}" method="POST" class="space-y-3 flex flex-col gap-3">
                    {% csrf_token %}
                    <div class="flex gap-3 flex-wrap *:grow items-center">
                        <div class="flex flex-col gap-2">
                            <label for="country">Country</label>
                            <input name="country" id="country" class="rounded-lg border p-3" value="{{request.user.profile.get_country}}" required>         
                        </div>
                        <div class="flex flex-col gap-3">
                            <label for="city">City</label>
                            <input name="city" id="city" class="rounded-lg border p-3" value="{{request.user.profile.get_city}}" required>
                        </div>
                    </div>
                    <div class="flex gap-3 flex-wrap items-center *:grow">
                        <div class="flex flex-col gap-3">
                            <select name="" id="" class="border rounded-lg p-3">
                                <option value="">+963</option>
                                <option value="">+44</option>
                                <option value="">+01</option>
                                <option value="">+07</option>
                                <option value="">+962</option>
                                <option value="">+964</option>
                                <option value="">+90</option>
                                <option value="">+70</option>
                                <option value="">+964</option>
                            </select>
                        </div>
                        <input type="text" placeholder="Phone Number" name="phone_number" class="rounded-lg border p-3" value="{{request.user.profile.phone_number}}" required>
                    </div>
                    <input type="submit" value="Save Address"
                        class="w-fit cursor-pointer bg-green-500 text-white py-4 px-6 rounded-lg border hover:bg-green-600 transition-colors">
                </form>
            </div>
            <div class="grow-[3]" x-show="openedIndex == 3" x-transition:enter>
                <form action="{% url 'users:save-names' %}" method="POST" class="flex flex-col gap-5" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h2 class="font-semibold text-xl">Account Details</h2>
                    <div class="flex gap-5">
                        <img src="{% if request.user.profile.image %} {{request.user.profile.image.url}}
                                {% else %} {% static 'images/default-account-image.png'%} {% endif %}" alt="" class="rounded-full size-24 object-cover">
                        <div>
                            <label class="block mb-2 text-sm font-medium text-gray-900" for="file_input">Upload file</label>
                            <input class="block p-4 w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none" name="image" type="file">
                        </div>
                    </div>
                    <div class="flex flex-col flex-wrap gap-3 *:grow">
                        <div class="flex flex-wrap gap-3 *:grow">
                            <div class="flex flex-col gap-1">
                                <label>First name</label>
                                <input type="text" name="first_name" class="border rounded-lg p-2 caret-slate-400" value="{{request.user.first_name}}">
                            </div>
                            <div class="flex flex-col gap-1">
                                <label>Last name</label>
                                <input type="text" name="last_name" class="border rounded-lg p-2 caret-slate-400" value="{{request.user.last_name}}">
                            </div>
                        </div>
                        <div class="flex flex-col gap-1 *:grow">
                            <label>Email Address</label>
                            <input type="email" name="email" class="border rounded-lg p-2 caret-slate-400" value="{{request.user.email}}">
                        </div>
                    </div>
                    <button
                        class="bg-green-500 text-white border rounded-lg p-4 hover:bg-amber-400 transition-colors self-start">Save
                        Profile</button>
                </form>
            </div>
            <div class="grow-[3] flex flex-col gap-3" x-show="openedIndex == 4" x-transition:enter>
                <p class="text-black text-lg">Are you sure you want to logout?</p>
                <form action="{% url 'users:logout-user' %}" method="POST">
                    {% csrf_token%}
                    <button class="w-fit bg-green-500 p-3 hover:hover:bg-green-600 text-white transition-colors rounded-lg">Confirm</button>
                </form>
                
                <p class="text-gray-500">* You won't be able to comment on products and rate them or rating the vendors.</p>
            </div>
        </div>
    </div>
</div>


{% include "partials/footer.html" %}

<div class="hidden fixed inset-0 bg-slate-200/75 z-[110]" id="theme"></div>

{% endblock content %}

Ecommerce/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/output.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}" />
    <!-- <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script> -->

    {% block head%}
    <title>Nest</title>
    {% endblock head%}
</head>

<body class="font-body">
    {% block content%}
    {% endblock content %}
    <script src="{% static 'js/alpine_output.js' %}" defer></script>
</body>

</html>

Ecommerce/templates/sign-up.html
{% extends 'main.html' %}
{% load static%}

{% block head %}
<title>Nest | Sign up</title>
{% endblock head%}


{% block content %}
{% include 'partials/navbar.html' with chosen='home'%}
{% include 'partials/path.html' with parent_page_name="Pages" page_name="Sign up"%}

<div class="container mx-auto px-4 my-16 lg:max-w-[1023.99px]">
    <div class="flex flex-col flex-wrap gap-10 items-center justify-center *:grow">
        <div class="space-y-2 self-start">
            <h1 class="font-bold text-4xl">Create an Account</h1>
            <p>Already have an account? <a href="{% url 'users:login-user' %}" class="text-green-500">Login</a></p>
        </div>
        <div class="flex flex-col  gap-10 w-full px-5 sm:px-0 *:sm:w-1/2 ">
            <form action="{% url 'users:register-user' %}" method="POST">
                <div class="flex flex-col gap-5 *:border *:rounded-lg *:p-3 *:outline-slate-400 *:grow">
                    {% csrf_token %}
                    <input type="text" placeholder="Username" name="username" class="placeholder:text-gray-500" required>
                    <input type="text" placeholder="Email" name="email" class="placeholder:text-gray-500" required>
                    <input type="password" placeholder="Password" name="password" class="placeholder:text-gray-500" required>
                    <button type="submit" class="bg-green-500 hover:bg-green-600 hover:-translate-y-1 transition-[background-color,transform] rounded-lg text-white p-2 w-fit">
                        Submit & register</button>
                    <p class="text-gray-500 text-sm !border-none">
                        Notice: Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our 
                        <a href="{% url 'services:privacy-policy'%}" class="text-green-500 underline hover:text-green-600">privacy policy</a>. </p>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock content %}